/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PupilsIndexRouteImport } from './routes/pupils/index'
import { Route as PupilsAddIndexRouteImport } from './routes/pupils/add/index'
import { Route as PupilsIdIndexRouteImport } from './routes/pupils/$id/index'
import { Route as PupilsIdEditIndexRouteImport } from './routes/pupils/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIndexRoute = PupilsIndexRouteImport.update({
  id: '/pupils/',
  path: '/pupils/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsAddIndexRoute = PupilsAddIndexRouteImport.update({
  id: '/pupils/add/',
  path: '/pupils/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdIndexRoute = PupilsIdIndexRouteImport.update({
  id: '/pupils/$id/',
  path: '/pupils/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdEditIndexRoute = PupilsIdEditIndexRouteImport.update({
  id: '/pupils/$id/edit/',
  path: '/pupils/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pupils': typeof PupilsIndexRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
  '/pupils/add': typeof PupilsAddIndexRoute
  '/pupils/$id/edit': typeof PupilsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pupils': typeof PupilsIndexRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
  '/pupils/add': typeof PupilsAddIndexRoute
  '/pupils/$id/edit': typeof PupilsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pupils/': typeof PupilsIndexRoute
  '/pupils/$id/': typeof PupilsIdIndexRoute
  '/pupils/add/': typeof PupilsAddIndexRoute
  '/pupils/$id/edit/': typeof PupilsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pupils'
    | '/pupils/$id'
    | '/pupils/add'
    | '/pupils/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pupils' | '/pupils/$id' | '/pupils/add' | '/pupils/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/pupils/'
    | '/pupils/$id/'
    | '/pupils/add/'
    | '/pupils/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PupilsIndexRoute: typeof PupilsIndexRoute
  PupilsIdIndexRoute: typeof PupilsIdIndexRoute
  PupilsAddIndexRoute: typeof PupilsAddIndexRoute
  PupilsIdEditIndexRoute: typeof PupilsIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/': {
      id: '/pupils/'
      path: '/pupils'
      fullPath: '/pupils'
      preLoaderRoute: typeof PupilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/add/': {
      id: '/pupils/add/'
      path: '/pupils/add'
      fullPath: '/pupils/add'
      preLoaderRoute: typeof PupilsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/': {
      id: '/pupils/$id/'
      path: '/pupils/$id'
      fullPath: '/pupils/$id'
      preLoaderRoute: typeof PupilsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/edit/': {
      id: '/pupils/$id/edit/'
      path: '/pupils/$id/edit'
      fullPath: '/pupils/$id/edit'
      preLoaderRoute: typeof PupilsIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PupilsIndexRoute: PupilsIndexRoute,
  PupilsIdIndexRoute: PupilsIdIndexRoute,
  PupilsAddIndexRoute: PupilsAddIndexRoute,
  PupilsIdEditIndexRoute: PupilsIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
